### PR TITLE
Services are rendering except Mason's it looks like

### PR DESCRIPTION
**Pull request by jacobwilson41**
Screen Shot 2020-03-25 at 2 27 23 PM

### CODE REVIEW

**Comment by jacobwilson41** [comment]
@JonBaltz @cranjis-mcbasketball @anthony-ha

**Comment by JonBaltz** [comment]
Mason's is rendering(the read more button) but it doesn't have any pictures

**Comment by JonBaltz** [comment]
Also It looks good code-wise. b

**Comment by jacobwilson41** [comment]
I forgot to load in Mason's styles too so thats why it wasn't fully rendering

**Pull request merged**
